export enum ContentState {
  DISPLAYING = 'DISPLAYING',
  CREATING = 'CREATING',
  EDITING = 'EDITING',
  DISABLING = 'DISABLING',
  DELETING = 'DELETING',
  CONFIRM_DELETE = 'CONFIRM_DELETE',
  SAVING_EDIT = 'SAVING_EDIT',
  SAVING_CREATE = 'SAVING_CREATE',
}
