export default [
  {
    id: '59e7a13d5b24bf69e9a02d1b',
    role: 'ADMIN',
    status: 'Active',
    firstName: 'Glenda',
    lastName: 'Mcgowan',
    createdAt: 'Sat Mar 25 2000 18:33:29 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'glenda.mcgowan@gmail',
    userName: 'glenda.mcgowan@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e4ffa252c0231964a0c44a',
    userName: 'hesternash@otherside.com',
    email: 'hesternash@otherside.com',
    role: 'USER',
    status: 'Active',
    firstName:
      'Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu',
    lastName:
      'Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu',
    createdAt: 'Mon Oct 16 18:24:25 UTC 2017',
    lastLogin: null,
    preferredLanguage: null,
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d5153904ad7fd195a',
    role: 'ADMIN',
    status: 'Deactivated',
    firstName: 'Cunningham',
    lastName: 'Hoffman',
    createdAt: 'Sun Sep 25 2005 18:51:16 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'cunningham.hoffman@gmail',
    userName: 'cunningham.hoffman@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d60dd7fa018e0a0b1',
    role: 'USER',
    status: 'Deactivated',
    firstName: 'Gladys',
    lastName: 'Gutierrez',
    createdAt: 'Thu Apr 06 2000 00:35:01 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'gladys.gutierrez@gmail',
    userName: 'gladys.gutierrez@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d0180a0df8aadb836',
    role: 'USER',
    status: 'Active',
    firstName: 'Greta',
    lastName: 'Cobb',
    createdAt: 'Sat Feb 08 2003 09:43:05 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'greta.cobb@gmail',
    userName: 'greta.cobb@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13dd723c3d728109f2e',
    role: 'USER',
    status: 'Active',
    firstName: 'Cooke',
    lastName: 'Montgomery',
    createdAt: 'Fri Dec 09 1994 05:05:13 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'cooke.montgomery@gmail',
    userName: 'cooke.montgomery@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d696cc80a95727aff',
    role: 'USER',
    status: 'Active',
    firstName: 'Deidre',
    lastName: 'Cote',
    createdAt: 'Sat Jul 22 1989 22:13:51 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'deidre.cote@gmail',
    userName: 'deidre.cote@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d7b096515e7c9305d',
    role: 'USER',
    status: 'Active',
    firstName: 'Whitehead',
    lastName: 'Terry',
    createdAt: 'Sun Jul 22 2007 18:28:32 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'whitehead.terry@gmail',
    userName: 'whitehead.terry@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d5144666e9ffb660f',
    role: 'USER',
    status: 'Active',
    firstName: 'Merritt',
    lastName: 'Dorsey',
    createdAt: 'Sat May 29 1971 18:37:28 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'merritt.dorsey@gmail',
    userName: 'merritt.dorsey@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13dc0299cddcbeed254',
    role: 'USER',
    status: 'Active',
    firstName: 'Eliza',
    lastName: 'Keith',
    createdAt: 'Thu Feb 06 1986 00:42:53 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'eliza.keith@gmail',
    userName: 'eliza.keith@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d98697efe63b80f21',
    role: 'USER',
    status: 'Active',
    firstName: 'Hazel',
    lastName: 'Vinson',
    createdAt: 'Sat Jun 02 2001 15:49:54 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'hazel.vinson@gmail',
    userName: 'hazel.vinson@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d805addd2cd0aedba',
    role: 'USER',
    status: 'Active',
    firstName: 'Theresa',
    lastName: 'Beck',
    createdAt: 'Fri Apr 27 1979 05:56:49 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'theresa.beck@gmail',
    userName: 'theresa.beck@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d0849a389f1d29d94',
    role: 'USER',
    status: 'Active',
    firstName: 'Haney',
    lastName: 'Erickson',
    createdAt: 'Sun Jan 11 2015 21:05:41 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'haney.erickson@gmail',
    userName: 'haney.erickson@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d00c1d1c46f7a64cf',
    role: 'USER',
    status: 'Active',
    firstName: 'Suzanne',
    lastName: 'Ware',
    createdAt: 'Tue Dec 15 2015 11:55:42 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'suzanne.ware@gmail',
    userName: 'suzanne.ware@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d390f508292fdc5cd',
    role: 'USER',
    status: 'Active',
    firstName: 'Leon',
    lastName: 'Sanders',
    createdAt: 'Wed Nov 18 2015 17:35:37 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'leon.sanders@gmail',
    userName: 'leon.sanders@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d783a51f55f6b8c28',
    role: 'USER',
    status: 'Active',
    firstName: 'Pittman',
    lastName: 'Nash',
    createdAt: 'Tue Oct 26 1993 17:37:23 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'pittman.nash@gmail',
    userName: 'pittman.nash@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d1077dd8760a922d3',
    role: 'USER',
    status: 'Active',
    firstName: 'Pruitt',
    lastName: 'Robles',
    createdAt: 'Wed Jul 11 1979 11:23:35 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'pruitt.robles@gmail',
    userName: 'pruitt.robles@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d1f3df9fdb8fd2681',
    role: 'USER',
    status: 'Active',
    firstName: 'Joann',
    lastName: 'Conley',
    createdAt: 'Fri Jun 28 2002 06:11:24 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'joann.conley@gmail',
    userName: 'joann.conley@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d5b76f60c215d1aa9',
    role: 'USER',
    status: 'Active',
    firstName: 'Holder',
    lastName: 'Ewing',
    createdAt: 'Wed Feb 12 1986 11:10:07 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'holder.ewing@gmail',
    userName: 'holder.ewing@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d665866c34016c354',
    role: 'USER',
    status: 'Active',
    firstName: 'Imogene',
    lastName: 'Rhodes',
    createdAt: 'Wed May 20 2015 14:29:48 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'imogene.rhodes@gmail',
    userName: 'imogene.rhodes@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d8a2c906511a18cfc',
    role: 'USER',
    status: 'Active',
    firstName: 'Norma',
    lastName: 'Simmons',
    createdAt: 'Sat Sep 01 1973 19:51:37 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'norma.simmons@gmail',
    userName: 'norma.simmons@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d30a03defc0ead330',
    role: 'USER',
    status: 'Active',
    firstName: 'Winnie',
    lastName: 'Vincent',
    createdAt: 'Mon Sep 09 1985 12:09:30 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'winnie.vincent@gmail',
    userName: 'winnie.vincent@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d25089d52b908f6df',
    role: 'USER',
    status: 'Active',
    firstName: 'Samantha',
    lastName: 'Sosa',
    createdAt: 'Sun Apr 16 1989 03:04:29 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'samantha.sosa@gmail',
    userName: 'samantha.sosa@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d1d41dc0295d27c09',
    role: 'USER',
    status: 'Active',
    firstName: 'Mclean',
    lastName: 'Carey',
    createdAt: 'Fri Mar 27 1981 22:44:55 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'mclean.carey@gmail',
    userName: 'mclean.carey@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13dbd55f6a6d772704c',
    role: 'USER',
    status: 'Active',
    firstName: 'Hallie',
    lastName: 'Barton',
    createdAt: 'Sun Dec 10 1995 14:25:26 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'hallie.barton@gmail',
    userName: 'hallie.barton@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13d1fc1dcb3b5007fbe',
    role: 'USER',
    status: 'Active',
    firstName: 'Potter',
    lastName: 'Barber',
    createdAt: 'Tue Aug 06 1985 06:04:14 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'potter.barber@gmail',
    userName: 'potter.barber@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e59a0b18d467299df',
    role: 'USER',
    status: 'Active',
    firstName: 'Donaldson',
    lastName: 'Rogers',
    createdAt: 'Fri Mar 20 2009 12:42:22 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'donaldson.rogers@gmail',
    userName: 'donaldson.rogers@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e9d2402011a54deb4',
    role: 'USER',
    status: 'Active',
    firstName: 'Coleen',
    lastName: 'Johns',
    createdAt: 'Tue Oct 21 2014 11:14:36 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'coleen.johns@gmail',
    userName: 'coleen.johns@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e7c2a9c11412b9965',
    role: 'USER',
    status: 'Active',
    firstName: 'Beatriz',
    lastName: 'Norris',
    createdAt: 'Sun Apr 06 1980 00:08:41 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'beatriz.norris@gmail',
    userName: 'beatriz.norris@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ed4b6ad1ed42be92c',
    role: 'USER',
    status: 'Active',
    firstName: 'Jeanette',
    lastName: 'Hodge',
    createdAt: 'Mon May 30 2011 19:37:38 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'jeanette.hodge@gmail',
    userName: 'jeanette.hodge@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e26b044b1d90ee70a',
    role: 'USER',
    status: 'Active',
    firstName: 'Shauna',
    lastName: 'Clarke',
    createdAt: 'Wed Dec 02 2009 23:04:04 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'shauna.clarke@gmail',
    userName: 'shauna.clarke@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13edaa965a141839001',
    role: 'USER',
    status: 'Active',
    firstName: 'George',
    lastName: 'Sparks',
    createdAt: 'Fri Sep 19 2008 21:16:14 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'george.sparks@gmail',
    userName: 'george.sparks@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e5ca8fbb0af8c195f',
    role: 'USER',
    status: 'Active',
    firstName: 'Tyler',
    lastName: 'York',
    createdAt: 'Sat Oct 10 2009 17:57:02 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'tyler.york@gmail',
    userName: 'tyler.york@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e3c53a968d56db795',
    role: 'USER',
    status: 'Active',
    firstName: 'Griffin',
    lastName: 'Nichols',
    createdAt: 'Thu Feb 15 2001 08:14:47 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'griffin.nichols@gmail',
    userName: 'griffin.nichols@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e4d9d7634c9c091f4',
    role: 'USER',
    status: 'Active',
    firstName: 'Silva',
    lastName: 'Mcleod',
    createdAt: 'Tue Jan 27 1976 22:27:02 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'silva.mcleod@gmail',
    userName: 'silva.mcleod@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ec83e42e54a6444ad',
    role: 'USER',
    status: 'Active',
    firstName: 'Burgess',
    lastName: 'Shepard',
    createdAt: 'Mon May 11 2015 17:13:46 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'burgess.shepard@gmail',
    userName: 'burgess.shepard@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e5e95fb36eac45367',
    role: 'USER',
    status: 'Active',
    firstName: 'Felicia',
    lastName: 'Marshall',
    createdAt: 'Mon Oct 08 1973 18:43:04 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'felicia.marshall@gmail',
    userName: 'felicia.marshall@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e05b1ce18faaaf307',
    role: 'USER',
    status: 'Active',
    firstName: 'Rena',
    lastName: 'Riley',
    createdAt: 'Mon May 29 1989 10:09:36 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'rena.riley@gmail',
    userName: 'rena.riley@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e484ed9215efff11c',
    role: 'USER',
    status: 'Active',
    firstName: 'Ferguson',
    lastName: 'Larsen',
    createdAt: 'Fri Dec 15 2006 21:23:29 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'ferguson.larsen@gmail',
    userName: 'ferguson.larsen@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e4e2c21f719da11a1',
    role: 'USER',
    status: 'Active',
    firstName: 'Shelia',
    lastName: 'Hayden',
    createdAt: 'Sat Dec 24 1977 19:32:22 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'shelia.hayden@gmail',
    userName: 'shelia.hayden@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ee70275b8c66543de',
    role: 'USER',
    status: 'Active',
    firstName: 'Margie',
    lastName: 'Avery',
    createdAt: 'Wed Feb 03 1988 12:48:32 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'margie.avery@gmail',
    userName: 'margie.avery@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e03be3e6d16968df0',
    role: 'USER',
    status: 'Active',
    firstName: 'Joy',
    lastName: 'Medina',
    createdAt: 'Sat Jan 01 1977 12:42:01 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'joy.medina@gmail',
    userName: 'joy.medina@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ebbae52986adf1eb2',
    role: 'USER',
    status: 'Active',
    firstName: 'Angelia',
    lastName: 'Reese',
    createdAt: 'Thu Jul 01 1982 19:59:23 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'angelia.reese@gmail',
    userName: 'angelia.reese@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13effbb41db4b0e9f23',
    role: 'USER',
    status: 'Active',
    firstName: 'Marina',
    lastName: 'Wiggins',
    createdAt: 'Sat May 01 2004 20:31:28 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'marina.wiggins@gmail',
    userName: 'marina.wiggins@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e559386cd644be848',
    role: 'USER',
    status: 'Active',
    firstName: 'Buchanan',
    lastName: 'Mendoza',
    createdAt: 'Thu Jun 11 1992 03:41:51 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'buchanan.mendoza@gmail',
    userName: 'buchanan.mendoza@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ee764bea2f36d25d9',
    role: 'USER',
    status: 'Active',
    firstName: 'Farley',
    lastName: 'Garrett',
    createdAt: 'Sun Mar 14 1971 14:03:47 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'farley.garrett@gmail',
    userName: 'farley.garrett@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e16560a0088d93cbe',
    role: 'USER',
    status: 'Active',
    firstName: 'Reyes',
    lastName: 'Stein',
    createdAt: 'Thu May 19 1988 23:23:42 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'reyes.stein@gmail',
    userName: 'reyes.stein@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ea7b69db6c1cc195e',
    role: 'USER',
    status: 'Active',
    firstName: 'Fitzgerald',
    lastName: 'Doyle',
    createdAt: 'Tue Apr 30 2013 07:54:59 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'fitzgerald.doyle@gmail',
    userName: 'fitzgerald.doyle@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e56219b4f684db905',
    role: 'USER',
    status: 'Active',
    firstName: 'Bianca',
    lastName: 'Terrell',
    createdAt: 'Sun Dec 12 1971 06:37:04 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'bianca.terrell@gmail',
    userName: 'bianca.terrell@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13e7f040f9a259af532',
    role: 'USER',
    status: 'Active',
    firstName: 'Sharlene',
    lastName: 'Nielsen',
    createdAt: 'Sat Jan 01 2011 13:45:12 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'sharlene.nielsen@gmail',
    userName: 'sharlene.nielsen@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13ea9ca1e5d17971269',
    role: 'USER',
    status: 'Active',
    firstName: 'Sallie',
    lastName: 'Justice',
    createdAt: 'Sun May 27 2007 22:36:38 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'sallie.justice@gmail',
    userName: 'sallie.justice@gmail',
    groups: [],
    applications: [],
  },
  {
    id: '59e7a13eb1b8c9482b802de1',
    role: 'USER',
    status: 'Active',
    firstName: 'Wanda',
    lastName: 'Faulkner',
    createdAt: 'Sat Dec 05 1992 16:15:32 GMT+0000 (UTC)',
    lastLogin: null,
    preferredLanguage: null,
    email: 'wanda.faulkner@gmail',
    userName: 'wanda.faulkner@gmail',
    groups: [],
    applications: [],
  },
];
